import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import Image from "next/image";
import { useWindowSize } from "../hooks/useWindowSize";

const Home: NextPage = () => {
  const size = useWindowSize();
  return (
    <>
      <Head>
        <title>Psi.Entreno</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="min-h-scree h-fit bg-black">
        <nav className="sticky top-0 z-30 flex h-24 w-full flex-wrap items-center justify-around bg-white px-3">
          <div className="ml-16 mr-16 flex flex-shrink-0 items-center text-white">
            <span className="mb-3 text-xl font-semibold tracking-tight">
              <Link href="/">
                <Image
                  src={"/images/logo.svg"}
                  alt="logo"
                  width="185"
                  height="50"
                />
              </Link>
            </span>
          </div>
          <div className="flex flex-grow items-center justify-around">
            <Link href="#">
              <span className="link-color mt-4 mr-4 block hover:text-gray-600 lg:mt-0 lg:inline-block">
                Sobre mí
              </span>
            </Link>
            <Link href="#">
              <span className="link-color mt-4 mr-4 block hover:text-gray-600 lg:mt-0 lg:inline-block">
                Servicios
              </span>
            </Link>
            <Link href="#">
              <span className="link-color mt-4 block hover:text-gray-600 lg:mt-0 lg:inline-block">
                Contacto
              </span>
            </Link>
            <Link href="#">
              <span className="bg-color-eve mt-0 block rounded py-3 px-4 text-white hover:bg-violet-900 lg:inline-block">
                Iniciar mi Entrenamiento Mental
              </span>
            </Link>
            <Link href="#">
              <span className="link-color mt-4 block hover:text-gray-600 lg:mt-0 lg:inline-block">
                Mi cuenta
              </span>
            </Link>
          </div>
        </nav>
        <section className="main-section flex h-screen w-full flex-1 flex-col items-center justify-center overflow-hidden text-center">
          <h1 className="text-5xl font-black text-white">
            HAGAMOS QUE TU MENTE <br /> JUEGUE A TU FAVOR
          </h1>
          <div className="wavy-background absolute bottom-0 w-full">
            <Image
              src={"/images/blue-background.svg"}
              alt="hero"
              width={size.width}
              height={0}
            />
          </div>
        </section>
        <section className="wavy-background-color section relative flex h-screen w-full flex-1 flex-col items-center justify-center text-center pb-48">
          <div className="face-logo absolute top-0">
            <Image
              src={"/images/face-logo.svg"}
              alt="hero"
              width={300}
              height={0}
            />
          </div>
          <h2 className="secondary-text-color mb-8 text-2xl font-bold">
            ¿Te interesa?
          </h2>
          <h1 className="text-5xl font-black text-white">
            Entrena con un psicólogo deportivo
            <br /> y lleva tu rendimiento <br /> deportivo al siguiente nivel
          </h1>
          <h3 className="text-white mt-6 ">
            Como psicologo deportivo es mucho lo que puedo hacer por ti.
          </h3>
        </section>
      </main>
    </>
  );
};

export default Home;

// const AuthShowcase: React.FC = () => {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined }
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// };
