import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Psi.Entreno</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-stone-700">
        <nav className="sticky top-0 z-30 px-3 flex h-24 w-full flex-wrap items-center justify-around bg-white">
          <div className="ml-16 mr-16 flex flex-shrink-0 items-center text-white">
            <span className="mb-3 text-xl font-semibold tracking-tight">
              <Link href="/">
                <Image
                  src={"/images/logo.svg"}
                  alt="logo"
                  width="185"
                  height="50"
                />
              </Link>
            </span>
          </div>
          <div className="flex flex-grow items-center justify-around">
            <Link href="#">
              <span className="link-color mt-4 mr-4 block hover:text-gray-600 lg:mt-0 lg:inline-block">
                Sobre mí
              </span>
            </Link>
            <Link href="#">
              <span className="link-color mt-4 mr-4 block hover:text-gray-600 lg:mt-0 lg:inline-block">
                Servicios
              </span>
            </Link>
            <Link href="#">
              <span className="link-color mt-4 block hover:text-gray-600 lg:mt-0 lg:inline-block">
                Contacto
              </span>
            </Link>
            <Link href="#">
              <span className="bg-color-eve block rounded py-3 px-4 text-white hover:bg-violet-900 mt-0 lg:inline-block">
                Iniciar mi Entrenamiento Mental
              </span>
            </Link>
            <Link href="#">
              <span className="link-color mt-4 block hover:text-gray-600 lg:mt-0 lg:inline-block">
                Mi cuenta
              </span>
            </Link>
          </div>
        </nav>
        <div className="flex flex-1 flex-col items-center justify-center px-20 text-center">
          <Image src="/images/handshake.png" alt="me" width="64" height="64" />
          aldhasd
        </div>
      </main>
    </>
  );
};

export default Home;

// const AuthShowcase: React.FC = () => {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined }
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// };
